### ISSUE TITLE
Review interpretation permissions

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#16]

**Comment by adrianq** [comment]
![Screenshot from 2018-01-02 15-37-53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537c7e24ebef97b1f959e61a/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37a3dd5b168ee17365258424baf53444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd59f242e14a51ad1b3060e3647b.png)

**Comment by tokland** [comment]
https://docs.google.com/spreadsheets/d/11_jFDV2o3iqORjXAOwYbz0Mule0ZaWKsWhvv2MauhwE/edit#gid=0

**Comment by tokland** [comment]
Tasks:

- [ ] Check if we can use object.access.{read,update,delete} for permissions of the favorite and interpretation.
- [ ] Refactor comments: 
  - [ ] A user should be able to edit/delete his own comments
  - [ ] A user should be able to comment on any interpretation he can see .

**Comment by tokland** [comment]
[ ]  Notify interpretation owners about mentioned users without read access

https://github.com/EyeSeeTea/dhis2-core/pull/39

**Comment by adrianq** [comment]
This has been done as part of 100 different tasks. Closing this!
