### ISSUE TITLE
Add toggle favorite star

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#17]
- [x] Add Graphical component (icon star)
- [x] Add API call

**Comment by tokland** [comment]
Pushed code to discuss the visual aspect. Branch "feature/favorite" in d2-analysis and dhis2-visualizer:

![star.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46fb809b31c0cfeb9ffbb049a15ee4d6730472242d06f1797587b478e81a2b540b5b4eac425e5612f5ff9b37b4f46d2ede0356b49b381d66cc2f10abb2831abe08b3298b4c8cb7b58e4cd2a5.png)c

**Comment by tokland** [comment]
- [ ] Once accepted, apply same to pivot-table, event-visualizer, events-report.

**Comment by adrianq** [comment]
PRs have been accepted. @tokland they left a comment in JIRA (https://jira.dhis2.org/browse/DHIS2-3426?focusedCommentId=16716&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16716), not sure what he is talking about but we can discuss tomorrow...

**Comment by tokland** [comment]
Feedback from dhis2:

```
okay so i have discussed it with our ux designer

for the star:

"Mark as favorite"
"Unmark as favorite"

megaphone:

"Subscribe to this {chart} and start receiving notifications"
"Unsubscribe from this {chart} and stop receiving notifications"

note that {chart} is dynamic

so for the PT app it should be "pivot table" 
```

**Comment by tokland** [comment]
Done:

https://github.com/dhis2/charts-app/pull/47
https://github.com/dhis2/pivot-tables-app/pull/95
https://github.com/dhis2/event-charts-app/pull/15
https://github.com/dhis2/event-reports-app/pull/18
