### ISSUE TITLE
Right side panel minor improvements

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#21]

**Comment by tokland** [comment]
https://jira.dhis2.org/browse/DHIS2-3427
https://github.com/dhis2/d2-analysis/pull/57

- [ ] "Reply" will be used in replacement of "Post Comment" as well as added to the comments.
- [ ] On the reply, the author will be automatically mentioned (@user)
- [ ] Layout cosmetics.

**Comment by adrianq** [comment]
@tokland  I updated the description of this card to reflect today conversation with the client. Let's chat tomorrow anyway...

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/dhis2-visualizer/pull/6
https://github.com/EyeSeeTea/d2-analysis/pull/22

Ready for testing in our repo before asking for upstream merging.
