### ISSUE TITLE
Right side panel on maps app

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#22]
- [x] Create fork in org EST. Work from master -> 2.30 (see mentions changes in analytics tools)
- [x] Add scrollable panel.
- [x] Add details panel
- [x] Implement `Write interpretation` modal (keep existing, without sharing, check multi-line styles like dashboard does)
- [x] Interpretation panel (check dashboard->interpretations views)
- [x] Add router to manage id/interpretationid query strings.
(No ckeditor nor mentions here)

**Comment by tokland** [comment]
All implemented except for the control of id/interpretationid, those are the views for now:

![Screenshot from 2018-04-04 09-53-07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd5b768ef1b36545c424eab53444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af443e34550a2163166ee647b.png)
![Screenshot from 2018-04-04 09-53-15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd5b768ef1b36545c424fa953444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af443e34550a2163e62e5647b.png)
![Screenshot from 2018-04-04 09-53-30.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd5b768ef1b36545c424dac53444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af443e34550a2163166e7647b.png)s/logi

**Comment by tokland** [comment]
Done. PR upstream.

**Comment by adrianq** [comment]
From their comments/chats:
- This should be a separate component as the same functionality is needed in the new Data Visualizer app.
- Implement test coverage

**Comment by tokland** [comment]
PR opened upstream for the d2-ui interpretations component: https://github.com/dhis2/d2-ui/pull/224

Usage demo: https://github.com/eyeseetea/d2-ui-playground

For now, d2-ui-interpretations cannot be integrated into maps-app, because this app uses the old infrastructure (d2-xyz instead of @dhis2/d2-xyz)
