### ISSUE TITLE
Performance analysis

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#27]
- [x] If everything can be found in the google doc, remove it from the wiki
- [x] Reproduce analysis for 2.28
- [x] Document analysis (https://docs.google.com/document/d/1eLcd-eN07v36cQ6y3IQ6u15IDrrqB7YRx9nGZ7iowvE/edit)
- [x] If performance is still bad -> do a deeper analysis in this order
   - [x] Tracker Capture
   - [x] Event Capture
   - [x] Data Capture
   - [x] Dashboard
- [ ] Once the apps are modified to work with 2.29, reproduce the analysis for this version
- [x] Add new graphs with concurrent 5 in tomcat (2.28)
- [x] Test dev.est (2.28/sierraleone) jmeter, only 1 instance (sync + usage). When no testing, re-start 8080 nrc. Jmeter from dhis2.android. New section in doc (isolated tests)

**Comment by tokland** [comment]
Performance in 2.28 is roughly equal to 2.27., I'll start deeper analysis.

**Comment by tokland** [comment]
Some recommendations regarding nginx/tomcat/dhis2/android apps:

https://docs.google.com/document/d/1F39b9Nu2Z461-KbytvaZ8_2k7jcMD1P0dP-NQYxhKlA/edit

The most relevant is the addition of `maxConnections="N"` in the Tomcat connector, that prevents the server hogging, which resulted in instances hangs.

**Comment by tokland** [comment]
- [ ] Write script to see mean time by user vs maxConnection: EC2 simulated-medium-2Gb/large-4G (dev.est)/xlarge-NG (android.dhis2).
- [ ] List of requests for sync/usage for each app.

**Comment by idelcano** [comment]
@ifoche Done.

- [x] Identify user-blocking calls in Android apps (Ina)

Could you check the checkbox? I do not have permission.

You can see the actions classified by blocking level in the wiki of each android app.

**Comment by tokland** [comment]
Info completed in https://docs.google.com/document/d/1eLcd-eN07v36cQ6y3IQ6u15IDrrqB7YRx9nGZ7iowvE/edit#heading=h.2ivdo75uzi5y

**Comment by tokland** [comment]
Added ab/jmeter results for [dhis2-android-capture](https://github.com/dhis2/dhis2-android-capture-app/tree/develop/)

https://docs.google.com/document/d/1eLcd-eN07v36cQ6y3IQ6u15IDrrqB7YRx9nGZ7iowvE/edit#

Dhis2 Capture App -> 2.29

**Comment by adrianq** [comment]
Thanks for this guys! We have just sent them the document and explain the details in a meeting. They seem to be quite happy with the work done so far.
