### ISSUE TITLE
Attribute subscriptions

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dhis2-core#28]
- [x] Replicate column favorites -> subcriptions API endpoints.
- [x] Replace star with bullhorn (non-selected: grey, selected: dark blue, background, 
 check android) Suggested icon: https://d30y9cdsu7xlg0.cloudfront.net/png/47654-200.png

**Comment by adrianq** [comment]
Icon UI => ![Screenshot from 2018-03-14 10-11-29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537c7e24ebef97b1f959e61a/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3783dd4b768ee1236505e424ca553444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af74be34f56a2123365e5647b.png)

**Comment by tokland** [comment]
Unsubscribed:

![s1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46fbc5d86fc093bb80e3ba40b01faad67c1123717b56a62927d5b470ef177f555f5f4daa480e5642eee59b69f7e8682fd70541b8937f5566c73a1badbd801ebe00b9298e4980b4b49801.png)

Subscribed:

![s2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46fbc6d86fc093bb80e3ba40b01faad67c1123717b56a62927d5b470ef177f555f5f4daa480e5642eee59b69f7e8682fd70541b8937f5566c43d1badbd801ebe00b9298e4981b0b99801.png)

**Comment by adrianq** [comment]
We have to document this task. Google drive can be found here: https://docs.google.com/document/d/15WwT7bdNAN-b4qT9Y3i6mv3cW2VYaPNacBbAw1I0BbM/edit Moving it back to test

**Comment by adrianq** [comment]
Document attached to the JIRA issue (https://jira.dhis2.org/browse/DHIS2-3425) and status moved to 'In Review'

**Comment by tokland** [comment]
- [ ] Frontend: use material design start: https://material.io/tools/icons/?search=star&icon=star&style=baseline

**Comment by tokland** [comment]
Pushed to our repo to the branches which dhis2/{d2-analysys,charts-app} PRs feed from.

https://github.com/dhis2/charts-app/pull/42
https://github.com/dhis2/d2-analysis/pull/61

![Screenshot from 2018-05-28 09-30-58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37e3dd7bb68ef1b36525f424ba453444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af14fe84e54a6123e6bef647b.png)

![Screenshot from 2018-05-28 09-31-16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37e3dd7bb68ef1b36525e424faa53444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af14fe84e54a6123e64e2647b.png)

**Comment by tokland** [comment]
- [ ] Grey star
