### ISSUE TITLE
Implement missing functionality in right side panel for maps app

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#30]
- [x] Use new d2-i18n translation infrastructure
- [x] Remove edit details button (Bjorn request)
- [x] Remove "Edit sharing settings" from the interpretations component (Bjorn request)
- [x] Implement some way so the parent can update name/description (Bjorn request) -> add prop lastUpdated.
- [x] Add ckeditor
- [x] Implement right side panel 'minor improvements' => See https://github.com/EyeSeeTea/dhis2-core/issues/21
- [x] Implement mentioning in right side panel
- [] Apply new markup (https://jira.dhis2.org/browse/DHIS2-3428) NOT FOR NOW

**Comment by tokland** [comment]
Upstream PRs open:

https://github.com/dhis2/d2-ui/pull/246
https://github.com/dhis2/maps-app/pull/13
