### ISSUE TITLE
Explore how to send emails for internal messages

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dhis2-core#31]
When a user creates-interpretation/likes-interpretation/creates-interpretation-comment an object (chart/pivot/...), an internal message from the system (no user sender) should be sent to users subscribed to that object. 

Explore how to get those internal messages to send a normal email to those users.

(hangout with adrian,  if required)

**Comment by tokland** [comment]
System messages are messages with `sender = null`.  Main code:

https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/message/DefaultMessageService.java#L154

Example of use:

https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultJobInstance.java#L97

**Comment by tokland** [comment]
System notifications sent to subscribers could also be sent also to feedback recipients:

http://localhost:8029/api/configuration/feedbackRecipients.json

Or General settings -> General -> Feedback recipients (select a user group)

And now in our script we could poll /api/messageConversations, with a filter on created:gt:DATE and send emails.

**Comment by adrianq** [comment]
Counterproposal from the client: Triggers in the database  (let's discuss tomorrow)

**Comment by tokland** [comment]
As we discussed, those triggers would be a custom addition to the client database, so no changes on dhis2-core. I'll close the issue for now, we'll open a new one with the implementation.
