### ISSUE TITLE
Documentation for interpretations/analytics

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#34]

**Comment by tokland** [comment]
- [ ] https://jira.dhis2.org/browse/DHIS2-2798 (Adrián)
- [ ] https://jira.dhis2.org/browse/DHIS2-3425 (Adrián, create PR dhis2-docs from docx in ticket)
- [ ] https://jira.dhis2.org/browse/DHIS2-3426 (Arnau):
  - [ ] Test case
  - [ ] Docs: 8.4 -> add sections favorites/subscribers
- [ ] https://jira.dhis2.org/browse/DHIS2-3427 (Arnau)
- [ ] https://jira.dhis2.org/browse/DHIS2-3422 (Arnau)

- Tests: Jira -> Tests -> Create test (check Adrian shared spreadsheet)
- https://docs.dhis2.org/master/ 
- https://github.com/dhis2/dhis2-docs
