### ISSUE TITLE
Subscriptions enhance

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dhis2-core#42]
Code:

- [x] Check single comment edit/create, no table is rendered (ex: http://localhost:8080/Fdhis-web-visualizer%2F%3Fid%3DHDEDqV3yv3H%26interpretationid%3DuM1dC5M9pgM)
- [x] Implement locale infrastructure. They have asked for Spanish, English and French. We will use the end point /api/userSettings/my-key?user=username&value=my-val
- [x] Timestamp cache by user (now is global)
- [x] Check global installation
- [x] Add dates to subject in mail
- [x] Privacy policy -> https://www.psi.org/about/privacy-notice/
- [x ] Check api /ID/data.png info (why app renders chart -when interpretation selected only- but api endpoint shows empty data). -> After run analytics, I always see data in graphs. 
- [x] Add clean up task. Delete public files older than 6 months (Pending confirmation)
- [x] Connect to POEditor [adrianq]

Review:

- [x] data endpoints with date (and orgUnits, which can be relative to user)

Questions [adrianq]:

- [x] newsletter: what if no events for a user?
- [x] Which email server on production?
- [x] Pro DB dump
- [ ] Servers (script storage, public assets server)
- [x] Privacy policy

**Comment by adrianq** [comment]
Everything on our side is done... just waiting for a few credentials
