### ISSUE TITLE
Improvements and bug fixing

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#5]
Features:
- [x] If a user can see a favorite, user should be able to add interpretations/ add comments.
- [x] In the dashboard, show the icon of interpretations, even when count = 0. When we click on it, the modal should open as usual. In the right side, description is displayed and a link "Post new interpretation" should show up. If we click on the link we go to the visualiser with the right side open  and the new interpretation box pre-open.
- [x] Edit/ delete comment directly in right panel. A user can edit/delete its own interpretation and a superuser can do it for everybody's interpretations.
- [x]  comment box pre-open on right panel when interpretation is opened.
- [x] Show more description text in right side panel (approx. 500 chars)

Bugs:
- [x] right panel gets depopulated when chart/ table 'update' action is completed. There is nothing to do about this for the moment. Further discussion needs to happen in order to understand what is the best approach
- [ ] Migrate interpretation modal dialog in dashboard to 2.26 and trunk. [Issue](https://github.com/EyeSeeTea/dashboard-app/issues/1)
- [x] Fix scroll bar in modal dialog. [Issue](https://github.com/EyeSeeTea/dhis2-core/issues/4)
- [x] 'write interpretations' button does not work in data visualizer. It might have to do with user sharing settings. In case the user is not part of a user group with edit rights for that visual, the button is not active.
![error on intepretation features](https://cloud.githubusercontent.com/assets/6850223/24269070/c400bbc0-1007-11e7-9ae7-b2be4c68135b.JPG)

**Comment by adrianq** [comment]
Updated tasks description above. 

A more detailed information about the last bug has been required

For now, I will start by investigating what needs to happen to implement the first feature. If any change in the API is needed or just client side changes

**Comment by adrianq** [comment]
Re the last bug, the sharing settings for some visualizations were not properly configured. Visualizations should have the Public Access set to 'Can edit and view' (see attached image) in order to allow another user to post an interpretation. All the others visualizations in the dashboard were already configured like that.  I have modified the settings for these visualizations so they can keep working for now:

https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=pajWHw8hpqW
https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=WBVkJUKnVmv
https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=yaaTekVpkp8
https://sandbox.psi-mis.org/dhis-web-pivot/index.html?id=GLcbuPvoXeD
https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=XFa1xw0nwoa
https://sandbox.psi-mis.org/dhis-web-pivot/index.html?id=zZbb6c4CtSm
https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=Dww7tBhTaKd
https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=rmVf1wjLJ0D
https://sandbox.psi-mis.org/dhis-web-pivot/index.html?id=OByMCNPMOhb
https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=ZuWEcVlXyDM
https://sandbox.psi-mis.org/dhis-web-visualizer/index.html?id=xzVWGWIPVcM



- [ ] The logic should be: If you can view a visualization object, you should be able to create an interpretation or, at least, receive a clear feedback message if you are not allowed to.

For now changing the sharing settings should do the trick.

**Comment by adrianq** [comment]
Use case for the client:
- public none
- county m&e: r/w
- program user group: read only

The user belongs to the Read Only Group

**Comment by adrianq** [comment]
First thing to check:
- [ ] A user can do comments in a Read only graph? What is the limitation? Server side or client side?

**Comment by tokland** [comment]
>  A user can do comments in a Read only graph? What is the limitation? Server side or client side?

When the user clicks on "Write interpretation", the JS code makes an Ajax call to get the sharing info of the favourite:

GET http://zaudera:9025/api/25/sharing?type=chart&id=XFa1xw0nwoa

On read/write access you get something like this:

```
{
  "meta": {
    "allowPublicAccess": false,
    "allowExternalAccess": false
  },
  "object": {
    "id": "XFa1xw0nwoa",
    "name": "TZ - eREF - Pilot Level - Number of referrals redeemed vs projection (last 4 weeks)",
    "displayName": "TZ - eREF - Pilot Level - Number of referrals redeemed vs projection (last 4 weeks)",
    "publicAccess": "rw------",
    "externalAccess": false,
    "user": {
      "id": "njY5ftqm5MB",
      "name": "Martin Dale"
    }
  }
}
```

On read-only access, you get a Forbidden/403  (You do not have manage access to this object."). 

Now, looking at the code you see that the sharing information is used only to instantiate a SharingWindow and get data from it. This sharing info is rendered below the comment box. If you open the interpretation window and then enable RO access, you can post the comment with no problems:

200 POST /api/25/interpretations/chart/XFa1xw0nwoa (body: "comment") 
200 POST /api/25/sharing?type=interpretation&id=v9i9SSFs1Hc
200 POST /api/25/sharing?type=chart&id=XFa1xw0nwoa

Conclusion: Yes, we should be able to allow comments on read-only favourites only with client-side changes (not trying to render the SharingWindow)

Files related:

d2-analysis/lib/ui/InterpretationWindow.js
d2-analysis/lib/ui/SharingWindow.js

**Comment by adrianq** [comment]
@tokland and if you want to create an interpretation from the dashboard? there is not  such a sharing ui in the dashboard...

**Comment by tokland** [comment]
No problem to create a problem in the dashboard-integration, as you say, there is no sharing ui there.

**Comment by adrianq** [comment]
- [ ] When sharing -> Public = None, user shouldn't be able to see the favourite
- [ ] When sharing -> Public = None, Edit description should be hidden client side and should be forbidden server side
- [ ] When sharing -> Public = None, Sharing should be hidden
- [ ] When sharing -> Public = Read-only, Edit description should be hidden client side and should be forbidden server side
- [ ] When sharing -> Public = Read-only, Sharing should be hidden client side
- [ ] When sharing -> Public = Read-only, Share interpretation panel should be displayed but with the sharing setting bottom panel hidden.

**Comment by tokland** [comment]
[ ] Merge last version of upstream dhis2-core/2.25
[ ] Main dashboard: show error message if user cannot add interpretation
[ ] Hide/show buttons: edit description/sharing (if sharing 200), write_interpretation/add_comment (if sharing 200 or 403).

**Comment by tokland** [comment]
Comments on last comments uploaded to PRs and dev.est, ready for review.

**Comment by adrianq** [comment]
@tokland I have created the PRs and I briefly chatted with them and they agreed to review them tomorrow probably. Last thing before closing this card. Can you release the latest changes (PR comments) in dev.est tomorrow, please?

**Comment by adrianq** [comment]
I am closing this card. If they come back with some feedback about the PRs we can create specifics cards to tackle them. I have created a jira issue re the problem to edit a favourite description for a non-admin user: https://jira.dhis2.org/browse/DHIS2-1554
