### ISSUE TITLE
Use the "access" object in the favorite API response to determine access instead of Patch call

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#55]
See -> https://github.com/dhis2/d2-analysis/pull/47

This needs PRs against v29 (+v30, non-existing now) and master.
 
- [x] Use access object
- [x] Internal PR
- [x] Upstream PR (v29, master)

**Comment by tokland** [comment]
v29: https://github.com/dhis2/d2-analysis/pull/77
master: https://github.com/dhis2/d2-analysis/pull/76
