### ISSUE TITLE
Create Script to migrate HTML in PSI

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#59]
[repo: estools]

SQL script that converts current PSI database HTML (descriptions, interpretations and comments) to new rich text.

- [x] updatedBy/lastUpdated on should not be modified -> SQL script
- [x] Html interpretation/comment. change html tags to markdown.
- [x] Convert favorites description.
Test with dev.est:/data/dhis2/latest.psi-mis.org_db_dhis2_2.30-ddfca0c_20180829T154251Z.sql.gz
- [x] Transform li/ol to hyphen.
- [ ] Test with latest dump (waiting for client)

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/ESTools/blob/feature/favorites-html-to-markdown-sql/DHIS2/misc/favorites-html-to-markdown.sql

**Comment by adrianq** [comment]
Script already sent to the client
