### ISSUE TITLE
Integrate d2-ui rich text in analytics tools

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#60]
- [x] https://jira.dhis2.org/browse/DHIS2-5492
- [x] https://jira.dhis2.org/browse/DHIS2-5494

(See Jennifer chat)

See https://github.com/dhis2/d2-ui/blob/master/examples/create-react-app/src/components/rich-text.js

**Comment by tokland** [comment]
- [ ] PR d2a/DV for v30
https://github.com/dhis2/d2-analysis/pull/86
https://github.com/dhis2/charts-app/pull/56
- [ ] Once validated, PT/ER/EV * v31/master.
