### ISSUE TITLE
Mention  polishing

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#61]
See https://jira.dhis2.org/browse/DHIS2-5483

Branches: v30, master

http://localhost:8080/api/charts/LW0O27b7TdD.json?fields=id,name,publicAccess,userAccesses,userGroupAccesses

http://localhost:8080/api/users.json?query=jo&fields=id,name,userGroups

**Comment by tokland** [comment]
https://github.com/dhis2/d2-analysis/pull/88
https://github.com/dhis2/d2-analysis/pull/89
