### ISSUE TITLE
Review interpretation links

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#64]
- IS OWNER | ALL: like, edit, delete, share, reply
- access.update: like, share, reply
- access.read: like, [reply -> NOT POSSIBLE BY NOW, BACKEND PROBLEM]

We will ask the client what to do as reply is not working as expected.

**Comment by adrianq** [comment]
See https://github.com/EyeSeeTea/interpretation-notification/issues/16 https://github.com/EyeSeeTea/interpretation-notification/issues/9

**Comment by tokland** [comment]
- [x] Report bug upstream: https://jira.dhis2.org/browse/DHIS2-5760
- [ ] Show reply also for read-only access to interpretation
