### ISSUE TITLE
Review user can only see R or R/W interpretations

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#65]

**Comment by adrianq** [comment]
See https://github.com/EyeSeeTea/interpretation-notification/issues/12

**Comment by tokland** [comment]
Problem was that interpretation is rw but favourite is private. Should not happen with sharing validations. 

- [ ] Filter by OBJECT_TYPE.access.read (on list and filters). It has to be done manuall, API fails with a 500:  https://leap.psi-mis.org/api/interpretations.json?fields=id,text,publicAccess,chart[access[read]]&filter=chart.access.read:eq:true.
